import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import javaRef from './__fixtures__/bloom-java.json';
import { bloomHour, bloomWindow, etInstants, etParts, bloomStatus } from './bloom';

const research = readFileSync(new URL('./__fixtures__/research-schedule.txt', import.meta.url), 'utf8')
  .trim().split('\n').map((l) => l.split(' ')) as [string, string][];

const epochDay = (iso: string) => Date.parse(`${iso}T00:00:00Z`) / 864e5;

describe('bloomHour matches the Java implementation', () => {
  // bloom-java.json was generated by running KamorisGlasses.bloomHour() verbatim on a JVM (Java 25) for
  // 2024-01-01..2034-12-31. The Java harness isn't committed because the upstream code is CC BY-NC-ND.
  it(`all ${javaRef.hours.length} days 2024-2034`, () => {
    const got = javaRef.hours.map((_, i) => bloomHour(javaRef.startEpochDay + i));
    expect(got).toEqual(javaRef.hours);
  });

  it.each(research)('research schedule %s -> %s:00', (date, hour) => {
    expect(bloomHour(epochDay(date))).toBe(Number(hour));
  });

  it('handles negative epoch days (pre-1970) without throwing', () => {
    const h = bloomHour(-1);
    expect(h).toBeGreaterThanOrEqual(0);
    expect(h).toBeLessThan(24);
  });
});

describe('Eastern-time clock handling', () => {
  it('ordinary hour maps to one instant (EDT, UTC-4)', () => {
    expect(etInstants('2026-09-24', 14)).toEqual([Date.parse('2026-09-24T18:00:00Z')]);
  });

  it('winter hour uses EST (UTC-5)', () => {
    expect(etInstants('2026-12-25', 13)).toEqual([Date.parse('2026-12-25T18:00:00Z')]);
  });

  it('fall-back 01:00 happens twice', () => {
    expect(etInstants('2026-11-01', 1)).toEqual([
      Date.parse('2026-11-01T05:00:00Z'),
      Date.parse('2026-11-01T06:00:00Z'),
    ]);
  });

  it('spring-forward 02:00 does not exist', () => {
    expect(etInstants('2028-03-12', 2)).toEqual([]);
  });

  it('etParts reads ET date and hour of an instant', () => {
    expect(etParts(Date.parse('2026-09-25T03:30:00Z'))).toEqual({ date: '2026-09-24', hour: 23 });
  });
});

describe('bloomWindow', () => {
  it('2026-09-24 is 14:00-15:00 ET', () => {
    expect(bloomWindow('2026-09-24')).toEqual({
      date: '2026-09-24', hour: 14,
      start: Date.parse('2026-09-24T18:00:00Z'), end: Date.parse('2026-09-24T19:00:00Z'),
    });
  });

  it('a 02:00 bloom on a spring-forward day is null (never happens)', () => {
    expect(bloomHour(epochDay('2028-03-12'))).toBe(2);
    expect(bloomWindow('2028-03-12')).toBeNull();
  });
});

describe('bloomStatus', () => {
  it('active during the window', () => {
    const s = bloomStatus(Date.parse('2026-09-24T18:30:00Z'));
    expect(s.active?.date).toBe('2026-09-24');
    expect(s.next.date).toBe('2026-09-25');
  });

  it('upcoming later the same day', () => {
    const s = bloomStatus(Date.parse('2026-09-24T12:00:00Z'));
    expect(s.active).toBeNull();
    expect(s.next.date).toBe('2026-09-24');
  });

  it('skips a day whose window already passed', () => {
    const s = bloomStatus(Date.parse('2026-09-24T20:00:00Z'));
    expect(s.next.date).toBe('2026-09-25');
    expect(s.next.hour).toBe(8);
  });
});
