// Minecraft 26.2 enchantment data (misode/mcmeta tags 26.2-data-json / 26.2-assets-json):
// tooltip order from tags/enchantment/tooltip_order.json, English names from lang/en_us.json, max_level per enchantment.
// [key, name, maxLevel] in tooltip order.
export const ENCHANTS = [
  ["binding_curse", "Curse of Binding", 1],
  ["vanishing_curse", "Curse of Vanishing", 1],
  ["riptide", "Riptide", 3],
  ["channeling", "Channeling", 1],
  ["wind_burst", "Wind Burst", 3],
  ["frost_walker", "Frost Walker", 2],
  ["lunge", "Lunge", 3],
  ["sharpness", "Sharpness", 5],
  ["smite", "Smite", 5],
  ["bane_of_arthropods", "Bane of Arthropods", 5],
  ["impaling", "Impaling", 5],
  ["power", "Power", 5],
  ["density", "Density", 5],
  ["breach", "Breach", 4],
  ["piercing", "Piercing", 4],
  ["sweeping_edge", "Sweeping Edge", 3],
  ["multishot", "Multishot", 1],
  ["fire_aspect", "Fire Aspect", 2],
  ["flame", "Flame", 1],
  ["knockback", "Knockback", 2],
  ["punch", "Punch", 2],
  ["protection", "Protection", 4],
  ["blast_protection", "Blast Protection", 4],
  ["fire_protection", "Fire Protection", 4],
  ["projectile_protection", "Projectile Protection", 4],
  ["feather_falling", "Feather Falling", 4],
  ["fortune", "Fortune", 3],
  ["looting", "Looting", 3],
  ["silk_touch", "Silk Touch", 1],
  ["luck_of_the_sea", "Luck of the Sea", 3],
  ["efficiency", "Efficiency", 5],
  ["quick_charge", "Quick Charge", 3],
  ["lure", "Lure", 3],
  ["respiration", "Respiration", 3],
  ["aqua_affinity", "Aqua Affinity", 1],
  ["soul_speed", "Soul Speed", 3],
  ["swift_sneak", "Swift Sneak", 3],
  ["depth_strider", "Depth Strider", 3],
  ["thorns", "Thorns", 3],
  ["loyalty", "Loyalty", 3],
  ["unbreaking", "Unbreaking", 3],
  ["infinity", "Infinity", 1],
  ["mending", "Mending", 1],
];
export const CURSES = new Set(['binding_curse', 'vanishing_curse']);
/** en_us only translates enchantment.level.1-10; higher levels show the raw key in vanilla. */
export const LEVELS = ["I","II","III","IV","V","VI","VII","VIII","IX","X"];
